// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmT5LaIHd3_3wcBZIGj4yhX77HMHpzBMA',
    appId: '1:1094178609956:web:727e835cb038e1f63831b1',
    messagingSenderId: '1094178609956',
    projectId: 'tsf-social-login',
    authDomain: 'tsf-social-login.firebaseapp.com',
    storageBucket: 'tsf-social-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaYOAX_olxMLDpCHIjOwj7IclkzMrPv8',
    appId: '1:1094178609956:android:503dfecba7c2b51b3831b1',
    messagingSenderId: '1094178609956',
    projectId: 'tsf-social-login',
    storageBucket: 'tsf-social-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWMdxeZCn3ZC031nIBnNmN5qIxDKDM6I',
    appId: '1:1094178609956:ios:5f54e289c81721b33831b1',
    messagingSenderId: '1094178609956',
    projectId: 'tsf-social-login',
    storageBucket: 'tsf-social-login.appspot.com',
    iosBundleId: 'com.example.socialloginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWMdxeZCn3ZC031nIBnNmN5qIxDKDM6I',
    appId: '1:1094178609956:ios:1ad802108bb4701c3831b1',
    messagingSenderId: '1094178609956',
    projectId: 'tsf-social-login',
    storageBucket: 'tsf-social-login.appspot.com',
    iosBundleId: 'com.example.socialloginapp.RunnerTests',
  );
}
